### PR TITLE
Feat/update

### PR DESCRIPTION
**Pull request by Tunmisesuliat**

### CODE REVIEW

**Review by akinjide — COMMENTED** [review]
Please add test and ignore .idea folder in .gitignore file

**Review by akinjide — COMMENTED** [review]
Please clean up code and export def declarations

**Review by akinjide — CHANGES_REQUESTED** [review]
Delete .idea folder and add to .gitignore file

**Review by mezlet — CHANGES_REQUESTED** [review]

**Review by akinjide — COMMENTED** [review]
Apply changes across code and add readme for running test

**Pull request merged**
